tinymce.addI18n('bn_BD', {
	"Redo": "আবার আগের মতো",
	"Undo": "পূর্বাবস্থায় যাও",
	"Cut": "কর্তন",
	"Copy": "অনুলিপি",
	"Paste": "প্রতিলেপন",
	"Select all": "সব নির্বাচন করুন",
	"New document": "নতুন নথি",
	"Ok": "ঠিক আছে",
	"Cancel": "বাতিল",
	"Visual aids": "দৃষ্টি সহায়ক",
	"Bold": "মোটা",
	"Italic": "ইটালিক",
	"Underline": "নিম্নরেখা",
	"Strikethrough": "কাটা দাগ",
	"Superscript": "সুপারস্ক্রিপ্ট",
	"Subscript": "সাবস্ক্রিপ্ট",
	"Clear formatting": "ফর্ম্যাটিং বাতিল করুন",
	"Align left": "বামে পাঠান",
	"Align center": "মাঝে পাঠান",
	"Align right": "ডানে পাঠান",
	"Justify": "উভয়প্রান্তে সারি করুন ",
	"Bullet list": "বুলেট তালিকা",
	"Numbered list": "সংখ্যাযুক্ত তালিকা",
	"Decrease indent": "ইন্ডেন্ট হ্রাস করুন ",
	"Increase indent": "ইন্ডেন্ট বাড়ান",
	"Close": "বন্ধ",
	"Formats": "বিন্যাস",
	"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "আপনার ব্রাউজার ক্লিপবোর্ডে সরাসরি অ্যাক্সেস সমর্থন করে না। দয়া করে Ctrl + X \ / C \ / V কীবোর্ড শর্টকাটগুলি ব্যবহার করুন।",
	"Headers": " শিরোনাম ",
	"Header 1": " শিরোনাম ১",
	"Header 2": " শিরোনাম ২",
	"Header 3": " শিরোনাম ৩",
	"Header 4": " শিরোনাম ৪",
	"Header 5": " শিরোনাম ৫",
	"Header 6": " শিরোনাম ৬",
	"Headings": "শিরোনাম",
	"Heading 1": "হেডিং ১",
	"Heading 2": "হেডিং ২",
	"Heading 3": "হেডিং ৩",
	"Heading 4": "হেডিং ৪",
	"Heading 5": "হেডিং ৫",
	"Heading 6": " হেডিং ৬",
	"Div": "ডিভ",
	"Pre": "প্রি",
	"Code": "কোড",
	"Paragraph": "অনুচ্ছেদ",
	"Blockquote": "ব্লককোট",
	"Inline": "ইনলাইন",
	"Blocks": "ব্লক",
	"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "পেস্ট এখন প্লেইন টেক্সট মোডে রয়েছে। আপনি এখন এই বিকল্প বন্ধ না করা পর্যন্ত বিষয়বস্তু এখন প্লেইন টেক্সট হিসাবে আটকানো হবে।",
	"Font Family": "ফন্টের ফ্যামিলি",
	"Font Sizes": "ফন্টের আকার",
	"Class": "ক্লাস",
	"Browse for an image": "ছবির জন্য অনুসন্ধান করুন",
	"OR": "অথবা",
	"Drop an image here": "এখানে একটি ছবি ধরে ছাড়ুন",
	"Upload": "আপলোড",
	"Block": "ব্লক",
	"Align": "বিন্যস্তকরা",
	"Default": "ডিফল্ট",
	"Circle": "বৃত্ত",
	"Disc": "ডিস্ক",
	"Square": "বর্গক্ষেত্র",
	"Lower Alpha": "ছোট আলফা",
	"Lower Greek": "ছোট গ্রিক",
	"Lower Roman": "ছোট রোমান",
	"Upper Alpha": "বড় আলফা",
	"Upper Roman": "বড় রোমান",
	"Anchor": "অ্যাংকর",
	"Name": "নাম",
	"Id": "আইডি",
	"Id should start with a letter, followed only by letters, numbers, dashes, dots, colons or underscores.": "আইডিটি অক্ষর দিয়ে শুরু করা উচিত এরপর অক্ষর, সংখ্যা, ড্যাশ, ডটস, কলোন বা আন্ডারস্কোর দেওয়া উচিত।",
	"You have unsaved changes are you sure you want to navigate away?": "আপনার অসংরক্ষিত পরিবর্তন আছে, আপনি কি নিশ্চিত যে আপনি অন্য যায়গায় যেতে চান?",
	"Restore last draft": "শেষ খসড়াতে ফেরন যান",
	"Special character": "বিশেষ অক্ষর",
	"Source code": "সোর্স কোড",
	"Insert\/Edit code sample": "কোডের নমুনা যুক্ত/সম্পাদনা করুন",
	"Language": "ভাষা",
	"Code sample": "কোডের নমুনা",
	"Color": "রঙ",
	"R": "R",
	"G": "G",
	"B": "B",
	"Left to right": "বাম থেকে ডান",
	"Right to left": "ডান থেকে বাম",
	"Emoticons": "ইমোটিকনস",
	"Document properties": "নথির বৈশিষ্টাবলী",
	"Title": "খেতাব",
	"Keywords": "কীওয়ার্ড",
	"Description": "বর্ণনা",
	"Robots": "রোবট",
	"Author": "লেখক",
	"Encoding": "এনকোডিং",
	"Fullscreen": "পূর্ণ পর্দা",
	"Action": "কাজ",
	"Shortcut": "শর্টকাট",
	"Help": "সাহায্য",
	"Address": "ঠিকানা",
	"Focus to menubar": "মেনুবারের উপর ফোকাস করুন",
	"Focus to toolbar": "টুলবারে ফোকাস করুন",
	"Focus to element path": "ইলিমেন্ট পাথে ফোকাস",
	"Focus to contextual toolbar": "প্রাসঙ্গিক টুলবারে ফোকাস করুন",
	"Insert link (if link plugin activated)": "লিঙ্ক সন্নিবেশ করুন (যদি লিঙ্ক প্লাগইন সক্রিয় করা হয়)",
	"Save (if save plugin activated)": "সংরক্ষণ করুন (সক্রিয় প্লাগইন সংরক্ষণ করুন)",
	"Find (if searchreplace plugin activated)": "অনুসন্ধান করুন (যদি অনুসন্ধানযোগ্য প্লাগইন সক্রিয় করা হয়)",
	"Plugins installed ({0}):": "প্লাগইন ইনস্টল ({0}):",
	"Premium plugins:": "প্রিমিয়াম প্লাগইন:",
	"Learn more...": "আরও জানুন ...",
	"You are using {0}": "আপনি যবহার করছেন{0}",
	"Plugins": "প্লাগইনগুলি",
	"Handy Shortcuts": "কুশলী শর্টকাটস",
	"Horizontal line": "অনুভূমিক রেখা",
	"Insert\/edit image": "যুক্ত/চিত্র সম্পাদনা করুন",
	"Image description": "ছবির বর্ণনা",
	"Source": "উৎস",
	"Dimensions": "মাত্রা",
	"Constrain proportions": "সীমাবদ্ধ অনুপাত",
	"General": "সাধারণ",
	"Advanced": "উন্নত",
	"Style": "স্টাইল",
	"Vertical space": "উল্লম্ব স্থান",
	"Horizontal space": "অনুভূমিক স্থান",
	"Border": "বর্ডার",
	"Insert image": "ছবি যুক্ত করান",
	"Image": "ছবি",
	"Image list": "ছবির তালিকা",
	"Rotate counterclockwise": "ঘড়ির কাঁটার বিপরীত দিকে ঘোরান",
	"Rotate clockwise": "ঘড়ির কাঁটার দিকে ঘোরান",
	"Flip vertically": "উলম্বভাবে উল্টান",
	"Flip horizontally": "অনুভূমিকভাবে উল্টান",
	"Edit image": "ছবি সম্পাদনা করুন",
	"Image options": "ছবির অপশন",
	"Zoom in": "জুম ইন",
	"Zoom out": "জুম আউট",
	"Crop": "কাটছাঁট করুন",
	"Resize": "পুনরায় আকার দিন",
	"Orientation": "দিকমুখিতা",
	"Brightness": "উজ্জ্বলতা",
	"Sharpen": "তীক্ষ্ণ করুন",
	"Contrast": "কনট্রাস্ট",
	"Color levels": "রঙের মাত্রা",
	"Gamma": "গামা",
	"Invert": "বিপরীত",
	"Apply": "প্রয়োগ",
	"Back": "পিছনে",
	"Insert date\/time": "তারিখ/সময় যুক্ত করুন",
	"Date\/time": "তারিখ/সময়",
	"Insert link": "লিঙ্ক যুক্ত করুন",
	"Insert\/edit link": " লিঙ্ক যুক্ত/সম্পাদনা করুন",
	"Text to display": "লেখা প্রদর্শন করুন",
	"Url": "ইউআরএল",
	"Target": "লক্ষ্য",
	"None": "কেউ না",
	"New window": "নতুন উইন্ডো",
	"Remove link": "লিঙ্ক সরান",
	"Anchors": "অ্যাঙ্করস",
	"Link": "লিঙ্ক",
	"Paste or type a link": "লিঙ্ক প্রতিলেপন বা টাইপ করুন",
	"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "আপনার প্রবেশ করা URL টি একটি ইমেল ঠিকানা বলে মনে হয়। আপনি কি mailto: যোগ করতে চান?",
	"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "আপনার প্রবেশ করা URLটি একটি বাহ্যিক লিঙ্ক বলে মনে হয়। আপনি কি প্রয়োজনীয় http: \ / \ / prefix যোগ করতে চান?",
	"Link list": "লিঙ্কের তালিকা",
	"Insert video": "ভিডিও যুক্তকরুন",
	"Insert\/edit video": "ভিডিও যুক্ত/সম্পাদনা করুন",
	"Insert\/edit media": "মিডিয়া যুক্ত/সম্পাদনা করুন",
	"Alternative source": "বিকল্প উৎস",
	"Poster": "পোস্টার",
	"Paste your embed code below:": "আপনার এম্বেড কোডটি প্রতিলেপন করুন",
	"Embed": "বসান",
	"Media": "মিডিয়া",
	"Nonbreaking space": "অবিভাজিত",
	"Page break": "পৃষ্ঠা বিরতি",
	"Paste as text": "টেক্সট হিসাবে প্রতিলেপন করুন",
	"Preview": "পূর্বরূপ",
	"Print": "ছাপুন",
	"Save": "সংরক্ষণ করুন",
	"Find": "খুঁজুন",
	"Replace with": "প্রতিস্থাপন",
	"Replace": "প্রতিস্থাপন করুন",
	"Replace all": "সমস্ত প্রতিস্থাপন",
	"Prev": "পূর্ব",
	"Next": "পরবর্তী",
	"Find and replace": "খুঁজুন ও প্রতিস্থাপন করুন",
	"Could not find the specified string.": "নির্দিষ্ট স্ট্রিং খুঁজে পাওয়া যায়নি।",
	"Match case": "ম্যাচ ক্ষেত্রে",
	"Whole words": "পূর্ণ শব্দ",
	"Spellcheck": "বানান যাচাই",
	"Ignore": "উপেক্ষা করুন",
	"Ignore all": "সবগুলো উপেক্ষা করুন",
	"Finish": "শেষ",
	"Add to Dictionary": "অভিধানে যুক্ত করুন",
	"Insert table": "টেবিল ঢোকান",
	"Table properties": "টেবিল বৈশিষ্ট্য",
	"Delete table": "টেবিল মুছুন",
	"Cell": "সেল",
	"Row": "সারি",
	"Column": "কলাম",
	"Cell properties": "সেল বৈশিষ্ট্য",
	"Merge cells": "সেল মার্জ করুন",
	"Split cell": "সেল স্প্লিট করুনঃ",
	"Insert row before": "সারিতে ঢোকানঃ",
	"Insert row after": "পরের সারিতে ঢোকানঃ",
	"Delete row": "সারি মুছুন",
	"Row properties": "সারির বৈশিষ্ট্যগুলি",
	"Cut row": "সারি কাটুন",
	"Copy row": "সারি অনুলিপি করুন",
	"Paste row before": "সারির আগে প্রতিলেপন করুন",
	"Paste row after": " সারির পরে প্রতিলেপন করুন ",
	"Insert column before": "আগে কলাম যুক্ত করুন",
	"Insert column after": "পরে কলাম যুক্ত করুন",
	"Delete column": "কলাম মুছুন",
	"Cols": "কলাম",
	"Rows": "সারি",
	"Width": "প্রস্থ",
	"Height": "উচ্চতা",
	"Cell spacing": "সেল ফাঁকা",
	"Cell padding": "সেল প্যাডিং",
	"Caption": "ক্যাপশন",
	"Left": "বাম",
	"Center": "কেন্দ্র",
	"Right": "রাইট",
	"Cell type": "সেলের প্রকার",
	"Scope": "সুযোগ",
	"Alignment": "সারিবদ্ধ",
	"H Align": "এইচ সারিবদ্ধ",
	"V Align": "V সারিবদ্ধ",
	"Top": "শীর্ষ",
	"Middle": "মধ্য",
	"Bottom": "নীচে",
	"Header cell": "হেডার সেল",
	"Row group": "সারি গ্রুপ",
	"Column group": "কলাম গ্রুপ",
	"Row type": "সারির টাইপ",
	"Header": "হেডার",
	"Body": "বডি",
	"Footer": "পাদটীকা",
	"Border color": "বর্ডারের রঙ",
	"Insert template": "টেমপ্লেট যুক্ত করুন",
	"Templates": "টেমপ্লেট",
	"Template": "টেমপ্লেট",
	"Text color": "লেখার রঙ",
	"Background color": "পেছনের রং",
	"Custom...": "কাস্টম ...",
	"Custom color": "কাস্টম রঙ",
	"No color": "কোন রং নেই",
	"Table of Contents": "সুচিপত্র",
	"Show blocks": "ব্লক দেখান",
	"Show invisible characters": "অদৃশ্য অক্ষর দেখান",
	"Words: {0}": "শব্দ: {0}",
	"{0} words": "{0} শব্দ",
	"File": "ফাইল",
	"Edit": "সম্পাদন করা",
	"Insert": "সন্নিবেশ",
	"View": "দৃশ্য",
	"Format": "বিন্যাস",
	"Table": "টেবিল",
	"Tools": "সরঞ্জামসমূহ",
	"Powered by {0}": "বাস্তবায়নে {0}",
	"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "রিচ টেক্সট এরিয়া মেনু জন্য ALT-F9 চাপুন টুলবারের জন্য ALT-F10 টিপুন সাহায্যের জন্য ALT-0 চাপুন",
});